version: '2.27.0'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - finance:/var/lib/postgresql/data
volumes:
  finance:



